# Generated by Django 3.0.8 on 2020-07-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200729_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='urgencia',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], default='NAO', max_length=3),
        ),
    ]
